= 设置指南

本文介绍如何启用 Istio 并在你的项目中使用它。

如果你使用 Istio 进行流量管理，则需要允许外部流量进入集群。在这种情况下，你将需要执行以下所有步骤。

== 先决条件

本指南假设你已经xref:installation-and-upgrade.adoc[安装 Rancher]，且已经xref:kubernetes-clusters-in-rancher-setup.adoc[配置了一个单独的 Kubernetes 集群]并要在该集群上安装 Istio。

集群中的节点必须满足 xref:../integrations-in-rancher/istio/cpu-and-memory-allocations.adoc[CPU 和内存要求]。

Istio 控制的工作负载和服务必须满足 https://istio.io/docs/setup/additional-setup/requirements/[Istio 要求]。

== 安装

[TIP]
.快速设置提示：
====

如果你不需要外部流量到达 Istio，而只想设置 Istio 以监控和跟踪集群内的流量，请跳过xref:../how-to-guides/advanced-user-guides/istio-setup-guide/set-up-istio-gateway.adoc[设置 Istio Gateway] 和xref:../how-to-guides/advanced-user-guides/istio-setup-guide/set-up-traffic-management.adoc[设置 Istio 的流量管理组件]步骤。
====


. xref:../how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-cluster.adoc[在集群中启用 Istio]
. xref:../how-to-guides/advanced-user-guides/istio-setup-guide/enable-istio-in-namespace.adoc[在要使用 Istio 的所有命名空间中启用 Istio]
. xref:../how-to-guides/advanced-user-guides/istio-setup-guide/use-istio-sidecar.adoc[添加注入了 Istio sidecar 的部署和服务]
. xref:../how-to-guides/advanced-user-guides/istio-setup-guide/set-up-istio-gateway.adoc[设置 Istio Gateway]
. xref:../how-to-guides/advanced-user-guides/istio-setup-guide/set-up-traffic-management.adoc[设置 Istio 的流量管理组件]
. xref:../how-to-guides/advanced-user-guides/istio-setup-guide/generate-and-view-traffic.adoc[生成流量并查看 Istio 的运行情况]
